### ISSUE TITLE
如何获取场景posWorld 和 normalWorld，保存成RenderTexture

### ISSUE THREAD

**Issue by Yuanzan** [QianMo/Awesome-Unity-Shader#2]
如何获取场景posWorld 和 normalWorld，保存成RenderTexture？保存的数据类型为ARGBFloat。

1. 创建1张RenderTexture，存储类型为ARGBFloat
rt0 = new RenderTexture(Screen.width, Screen.height, 0, RenderTextureFormat.ARGBFloat, RenderTextureReadWrite.sRGB);
            rt0.enableRandomWrite = true;
            rt0.Create();

2. Camera.setTargetBuffers(1, buffers)
RenderBuffer[] colorBuffers = new RenderBuffer[1]; 
colorBuffers[0] = rt0.colorBuffer; // SV_Target0
cam.SetTargetBuffers(colorBuffers, rt0.depthBuffer);

3. Camera.render()
cam.Render();

做完上面三步后 buffer里没有数据？求大神指点

**Comment by RikkaBunny** [comment]
Unity 里面有深度法线图 获取之后就可以得到深度和对应的法线&nbsp; ， 通过深度就可以重建世界坐标。 怎么操作可以google。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yuanzan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月19日(星期五) 晚上7:31
收件人:&nbsp;"QianMo/Awesome-Unity-Shader"<Awesome-Unity-Shader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[QianMo/Awesome-Unity-Shader] 如何获取场景posWorld 和 normalWorld，保存成RenderTexture (#2)





 
如何获取场景posWorld 和 normalWorld，保存成RenderTexture？保存的数据类型为ARGBFloat。
  
 
创建1张RenderTexture，存储类型为ARGBFloat
 rt0 = new RenderTexture(Screen.width, Screen.height, 0, RenderTextureFormat.ARGBFloat, RenderTextureReadWrite.sRGB);
 rt0.enableRandomWrite = true;
 rt0.Create();
 
 
 
Camera.setTargetBuffers(1, buffers)
 RenderBuffer[] colorBuffers = new RenderBuffer[1];
 colorBuffers[0] = rt0.colorBuffer; // SV_Target0
 cam.SetTargetBuffers(colorBuffers, rt0.depthBuffer);
 
 
 
Camera.render()
 cam.Render();
 
  
做完上面三步后 buffer里没有数据？求大神指点

**Comment by Yuanzan** [comment]
用camera.RenderWithShader来重新渲染场景，保存到buffer就可以了
